version: "3.7"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    user: 0:0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  mongodb-exporter:
    image: percona/mongodb_exporter:0.36.0
    container_name: mongodb-exporter
    restart: unless-stopped
    command:
      - --discovering-mode
      - --compatible-mode
      - --collector.diagnosticdata
      - --collector.collstats
      - --collector.replicasetstatus
      - --collector.dbstats
      - --collector.topmetrics
      - --collector.indexstats
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
    ports:
      - 9216:9216

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    ports:
      - 8081:8081

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro



volumes:
  mongodb-data:
  mongoexpress-data: